name: news_portal
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.5
  easy_extension:
    git:
      url: https://github.com/scadasystems/Easy-Extension.git
  lucide_icons_flutter: ^3.0.2
  easy_localization: ^3.0.7+1
  go_router: ^15.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
